packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25

  "@tanstack/react-query": ^5.61.0
  "@trpc/client": ^11.0.0-rc.638
  "@trpc/react-query": ^11.0.0-rc.638
  "@trpc/server": ^11.0.0-rc.638
  eslint: ^9.15.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.15
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1

  react19:
    react: rc
    react-dom: rc
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
    # Type clashes in monorepo when using R19 types
    # "@types/react": npm:types-react@rc
    # "@types/react-dom": npm:types-react-dom@rc
